### PR TITLE
Fix spaces in Typewriter-Regular to have same width as other characters

### LINKED ISSUE #1: Typewriter font missing regular space
We want the existing visible space character, but are missing a regular (invisible) space.

Once added, we can simplify `\verb` (see https://github.com/Khan/KaTeX/pull/614).

### PR DESCRIPTION
**Pull request by edemaine**
Manually override `0x20` (space) and `0x80` (nonbreaking space) characters in `Typewriter-Regular` font to have the same `advanceWidth` (525) as the other characters in the font.

This will fix #1, which will clean up `\verb`. Also fixes `\texttt`'s handling of spaces as reported in https://github.com/Khan/KaTeX/issues/1255

Here's a screenshot of KaTeX showing the new behavior:
image

For comparison, here's how it used to render:
image

This will require rerunning the metrics script if #42 gets merged first.

### CODE REVIEW

File: fontMetricsData.js [hunk 1]
```diff
@@ -2000,6 +2000,7 @@ export default {
         "57683": [0, 0.12, 0, 0, 0.45],
     },
     "Typewriter-Regular": {
+        "32": [0, 0, 0, 0, 0],
```
Comment (kevinbarabash) [inline fontMetricsData.js]: shouldn't one of these numbers be 0.525?

Comment (edemaine) [reply fontMetricsData.js]: Hmm, probably, although it matches the other space definitions in other fonts. Maybe a separate PR? (I think we're getting lucky because we don't use horizontal metrics yet.)

Comment (ylemkimon) [reply fontMetricsData.js]: @kevinbarabash @edemaine 
The width reported by `parse_ttfs` are incorrect in:
(i) units; they are not divided by `unitsPerEm`, so their numbers are x1000 larger
(ii) they are calculated by `glyph.xMax - glyph.xMin`, which may differ from actual width(`glyph.width`)

Comment (edemaine) [reply fontMetricsData.js]: Thanks for tracking this down, @ylemkimon!  I fixed this in #42. It seems to fix the space width issue too, though I haven't yet tried the two PRs together.

**Comment by edemaine** [comment]
I rebased and reran tye metrics script, so now the new space characters have the correct width. Should be good to go now.
